[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  NITRO_PRESET = "netlify"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Functions configuration
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# Edge functions configuration
# Note: Edge functions are defined as an array when needed
# Example:
# [[edge_functions]]
#   path = "/api/*"
#   function = "api-handler"