[build]
  publish = "dist"
  command = "npx nuxi generate"

[build.environment]
  NODE_VERSION = "20"

# Redirects for SPA fallback - static site generation
[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5920
  publish = ".output/public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
